development:
  adapter: mysql
  database: login
  host: localhost
  username: root
  password: 123456
test:
  adapter: mysql
  database: login_test
  host: localhost
  username: root
  password: 123456

production:
  adapter: mysql
  database: login_production
  host: localhost
  username: root
  password: 123456 